import type { Metadata } from "next";

import "./globals.css";
import { Inter } from "next/font/google";
import { Fira_Sans } from "next/font/google";

const fira_Sans = Fira_Sans(
  { weight: ['100','200','300','400','500','800',], subsets: ["latin"] },
  
  
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fira_Sans.className}>{children}</body>
    </html>
  );
}
